POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Unite Summit",
  "details": "Um evento para programadores",
  "maximumAttendees": 235
}

###
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Novo Evento",
  "details": null,
  "maximumAttendees": 1
}


###

POST http://localhost:3333/events/182f10c3-1d11-4463-8be3-687d42c6687b/attendees
Content-Type: application/json

{
  "name": "Renan Fachin",
  "email": "renan2@email.com"
}


###
GET http://localhost:3333/events/182f10c3-1d11-4463-8be3-687d42c6687b


###
GET http://localhost:3333/attendees/1/badge